version: '3'
name: ${DB_SERVER_NAME:?err}

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    ports:
      - ${HOST_PORT:?err}:5432
    volumes:
      - ../db/${DB_SERVER_NAME}:/var/lib/postgresql/data/
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB:?err}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s   

